### ISSUE TITLE
[firebase_functions/internal] Response is not valid JSON object.

### ISSUE THREAD

**Issue by SoftDevCHD** [HayesGordon/chatter#5]
I am getting an error when executing the callable. My code is identical to yours, so I'm not sure where to start:
```
final callable = FirebaseFunctions.instance
            .httpsCallable('createStreamUserAndGetToken');
final results = await callable();
```

Here is the call stack:
```
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
<asynchronous suspension>
 #2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:23:24)
 <asynchronous suspension>
 #3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:49:37)
 <asynchronous suspension>
 #4      FirebaseService.joinWithEmailAndPassword (package:thrills/util/firebase_service.dart:359:25)
 <asynchronous suspension>
 #5      _JoinState.build.<anonymous closure> (package:thrills/screens/join/join.dart:285:33)
 <asynchronous suspension>
```

**Comment by HayesGordon** [comment]
Guessing this is resolved 😃 ?

**Comment by SoftDevCHD** [comment]
Hi Hayes, yes I found my mistake. Since I specify the region in which my cloud functions "live" in my index.js file, I needed to specify it when invoking them like this:
```
FirebaseFunctions.instanceFor(region: "us-west2")
            .httpsCallable('getStreamUserToken');
```
